background {
  color = rgba(100,100,100,1)
  path = ~/art002e000190~large.jpg
  blur_passes = 2
}

animations {
  enabled = true
}

input-field {
  monitor = eDP-1
  size = 800,200
  position = 0, 0
  halign = center
  valign = center
  placeholder_text = Enter Password
  font_color = rgba(0,0,0,1)
  rounding = 0
  inner_color = rgba(125,125,125,1)
  outer_color = rgba(75,75,75,1)
  outline_thickness = 10
  fade_on_empty = false
  hide_on_empty = false
  hide_input = false
}

auth {
  fingerprint:enabled = true
}
